name: Deploy to Production Environment (FTP)

on:
  workflow_dispatch:
    inputs:
      confirm_deployment:
        description: '本番環境にデプロイしますか？ (yes/no)'
        required: true
        default: 'no'
        type: choice
        options:
        - 'no'
        - 'yes'
      deployment_note:
        description: 'デプロイメントの説明'
        required: false
        default: ''

jobs:
  validate-input:
    runs-on: ubuntu-latest
    steps:
    - name: Validate deployment confirmation
      run: |
        if [ "${{ github.event.inputs.confirm_deployment }}" != "yes" ]; then
          echo "❌ デプロイメントが確認されていません"
          exit 1
        fi
        echo "✅ デプロイメントが確認されました"

  deploy-production:
    runs-on: ubuntu-latest
    needs: validate-input
    environment: production
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: main
        
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, json, mysqli
        
    - name: Create production deployment package
      run: |
        echo "📦 本番用デプロイパッケージを作成中..."
        
        # 必要なディレクトリを作成
        mkdir -p uploads temp logs cache backups
        
        # 本番用.htaccessファイルを作成
        cat > .htaccess << 'EOF'
        RewriteEngine On
        RewriteCond %{HTTPS} off
        RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
        Options -Indexes
        <Files ~ "^\.">
            Order allow,deny
            Deny from all
        </Files>
        <Files ~ "config\.php$">
            Order allow,deny
            Deny from all
        </Files>
        <Files ~ "backup\.php$">
            Order allow,deny
            Deny from all
        </Files>
        <Directory "uploads">
            php_flag engine off
            AddType text/plain .php .php3 .phtml .pht
        </Directory>
        <Directory "logs">
            Order allow,deny
            Deny from all
        </Directory>
        <Directory "backups">
            Order allow,deny
            Deny from all
        </Directory>
        php_value upload_max_filesize 10M
        php_value post_max_size 10M
        php_value max_execution_time 300
        php_value memory_limit 256M
        php_flag display_errors Off
        php_flag log_errors On
        EOF
        
        echo "✅ 本番用デプロイパッケージ作成完了"

    - name: Deploy to Production Server via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.PROD_FTP_SERVER }}
        username: ${{ secrets.PROD_FTP_USERNAME }}
        password: ${{ secrets.PROD_FTP_PASSWORD }}
        server-dir: ${{ secrets.PROD_FTP_SERVER_DIR }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.github/**
          **/tests/**
          **/.env
          **/README.md
          **/deploy-package/**
        
    - name: Verify production deployment
      run: |
        echo "🌐 本番環境URL: https://tw1nkle.com/Smiley/meal-delivery/billing-system/"
        echo "✅ 本番FTPデプロイ完了"
        
    - name: Send success notification
      if: success()
      run: |
        echo "🎉 本番環境へのFTPデプロイが成功しました！"
        echo "📍 確認URL: https://tw1nkle.com/Smiley/meal-delivery/billing-system/"
        echo "📝 デプロイメントの説明: ${{ github.event.inputs.deployment_note }}"
        echo "⚠️  本番環境の動作確認を行ってください"
        
    - name: Send failure notification  
      if: failure()
      run: |
        echo "❌ 本番環境へのFTPデプロイが失敗しました"
        echo "🔍 ログを確認してFTP設定を見直してください"
        echo "🚨 本番環境への影響を確認してください"
